<template>
  <div>
    <v-form-render :form-json="formJson" :form-data="formData" :option-data="optionData" ref="vFormRef"></v-form-render>
    <el-button type="primary" @click="submitForm">Submit</el-button>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { ElMessage } from 'element-plus'

const formJson = reactive({
  widgetList: [
    {
      type: 'static-text',
      icon: 'static-text',
      formItemFlag: false,
      options: {
        name: 'statictext111193',
        columnWidth: '200px',
        hidden: false,
        textContent: '单列表单',
        customClass: [],
        onCreated: '',
        onMounted: '',
        label: 'static-text',
      },
      id: 'statictext111193',
    },
    {
      type: 'divider',
      icon: 'divider',
      formItemFlag: false,
      options: {
        name: 'divider102346',
        label: '',
        columnWidth: '200px',
        direction: 'horizontal',
        contentPosition: 'center',
        hidden: false,
        customClass: [],
        onCreated: '',
        onMounted: '',
      },
      id: 'divider102346',
    },
    {
      type: 'input',
      icon: 'text-field',
      formItemFlag: true,
      options: {
        name: 'input12931',
        label: '用户名',
        labelAlign: 'label-center-align',
        type: 'text',
        defaultValue: '',
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: '',
        labelHidden: false,
        readonly: false,
        disabled: false,
        hidden: false,
        clearable: true,
        showPassword: false,
        required: true,
        validation: 'noChinese',
        validationHint: '请输入非中文字符',
        customClass: [],
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        minLength: 4,
        maxLength: 10,
        showWordLimit: false,
        prefixIcon: '',
        suffixIcon: '',
        appendButton: false,
        appendButtonDisabled: false,
        buttonIcon: 'el-icon-search',
        onCreated: '',
        onMounted: '',
        onInput: '',
        onChange: '',
        onFocus: '',
        onBlur: '',
        onValidate: '',
        requiredHint: '请输入用户名',
      },
      id: 'input12931',
    },
    {
      key: 84391,
      type: 'input',
      icon: 'text-field',
      formItemFlag: true,
      options: {
        name: 'input20992',
        label: '密码',
        labelAlign: '',
        type: 'password',
        defaultValue: '',
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: '',
        labelHidden: false,
        readonly: false,
        disabled: false,
        hidden: false,
        clearable: true,
        showPassword: true,
        required: true,
        requiredHint: '请输入密码',
        validation: 'noChinese',
        validationHint: '输入格式有误',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        minLength: null,
        maxLength: null,
        showWordLimit: false,
        prefixIcon: '',
        suffixIcon: '',
        appendButton: false,
        appendButtonDisabled: false,
        buttonIcon: 'custom-search',
        onCreated: '',
        onMounted: '',
        onInput: '',
        onChange: '',
        onFocus: '',
        onBlur: '',
        onValidate: '',
      },
      id: 'input20992',
    },
    {
      key: 84391,
      type: 'input',
      icon: 'text-field',
      formItemFlag: true,
      options: {
        name: 'input97418',
        label: '电子邮箱',
        labelAlign: '',
        type: 'text',
        defaultValue: '',
        placeholder: '',
        columnWidth: '200px',
        size: '',
        labelWidth: null,
        labelHidden: false,
        readonly: false,
        disabled: false,
        hidden: false,
        clearable: true,
        showPassword: false,
        required: true,
        requiredHint: '请输入邮箱',
        validation: 'email',
        validationHint: '请输入正确的邮箱',
        customClass: '',
        labelIconClass: null,
        labelIconPosition: 'rear',
        labelTooltip: null,
        minLength: null,
        maxLength: null,
        showWordLimit: false,
        prefixIcon: '',
        suffixIcon: '',
        appendButton: false,
        appendButtonDisabled: false,
        buttonIcon: 'custom-search',
        onCreated: '',
        onMounted: '',
        onInput: '',
        onChange: '',
        onFocus: '',
        onBlur: '',
        onValidate: '',
      },
      id: 'input97418',
    },
    {
      key: 18890,
      type: 'button',
      icon: 'button',
      formItemFlag: false,
      options: {
        name: 'button49098',
        label: '登录',
        columnWidth: '200px',
        size: '',
        displayStyle: 'block',
        disabled: false,
        hidden: false,
        type: 'primary',
        plain: true,
        round: false,
        circle: false,
        icon: null,
        customClass: '',
        onCreated: '',
        onMounted: '',
        onClick: '',
      },
      id: 'button49098',
    },
  ],
  formConfig: {
    modelName: 'formData',
    refName: 'vForm',
    rulesName: 'rules',
    labelWidth: 100,
    labelPosition: 'left',
    size: '',
    labelAlign: 'label-center-align',
    cssCode: '',
    customClass: [],
    functions: '',
    layoutType: 'H5',
    jsonVersion: 3,
    onFormCreated: '',
    onFormMounted: '',
    onFormDataChange: '',
  },
})
const formData = reactive({})
const optionData = reactive({})
const vFormRef = ref(null)

const submitForm = () => {
  (vFormRef?.value! as any)
    .getFormData()
    .then((formData: Record<string, any>) => {
      // Form Validation OK
      alert(JSON.stringify(formData))
    })
    .catch((error: string) => {
      // Form Validation failed
      ElMessage.error(error)
    })
}
</script>
